FROM node:16-alpine

WORKDIR /app

COPY . .

RUN yarn

FROM node:16-alpine

ENV NODE_ENV production

EXPOSE 5000

RUN mkdir /app && chown -R node:node /app

WORKDIR /app

USER node

RUN mkdir -p logs

COPY --chown=node:node ./package.json ./
COPY --chown=node:node .env.production .env

RUN yarn install --prod

COPY --from=0 --chown=node:node /app/src src

CMD ["yarn", "start"]